# This is a basic workflow that is manually triggered

name: Deploy API to EC2

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote-user: ec2-user
          server-ip: ${{ secrets.EC2_IP }}
          local-dir: ./your-project-directory
          remote-dir: /path/to/remote/directory



